### PR TITLE
Add Yield bearing extension for 6909

### PR DESCRIPTION
**Pull request by mergd**
Added a 6909 implementation that closely follows the Solmate 4626 implementation with an extra field for the tokenId.

Added tests as well.

### CODE REVIEW

**Comment by mergd** [comment]
Also created a simple [wrapper factory](https://github.com/mergd/6909-to-20-Factory) for 1155, 4626, and 20.

**Comment by jtriley-eth** [comment]
overall, looking pretty solid! atm, it looks like there's only a single asset you can deposit:
```solidity
// ..
    ERC20 public immutable asset; 
// ..
```
though the other functions contain a `tokenId` argument

what if we made a mapping of `tokenId` to asset? ie:
```solidity
    mapping(uint256 tokenId => ERC20 asset) public assets;
```
then just define the `tokenId` to be `uint256(uint160(address(asset)))`

this would allow 6909 to contain an arbitrary number of assets

**Comment by mergd** [comment]
Updated, there's an asset() and decimals() override :)

**Comment by mergd** [comment]
@jtriley-eth bumped to final 6909 spec, remove token supply and update tests

**Review by jtriley-eth — APPROVED** [review]
shipittttt

**Pull request merged**
